get:
  summary: Get the latest config of the Agent
  operationId: adminGetAgentConfig
  tags:
    - Admin
  parameters:
    - in: path
      name: id
      schema:
        type: integer
      description: Agent ID
  responses:
    "200":
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: "../../schemas/Config.yaml"
            required:
              - data
    "401":
      description: Unauthorized
    "404":
      description: Agent not found
    "500":
      $ref: "../../responses/500.yaml"
