patch:
  summary: Update a specific Config. Only draft configs can be updated.
  operationId: adminUpdateConfig
  tags:
    - Admin
  parameters:
    - in: path
      name: id
      schema:
        type: integer
        format: int64
      description: Config ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            user:
              type: string
            min_agent_version:
              type: string
            content:
              type: object
              additionalProperties:
                type: string
          required:
            - user
  responses:
    "200":
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: "../../schemas/Config.yaml"
            required:
              - data
    "401":
      description: Unauthorized
    "404":
      description: Config not found
    "500":
      $ref: "../../responses/500.yaml"
