post:
  summary:
    Submit the Deployment for reviewing. Only draft deployments can be submitted.
    After submitting, the deployment will be in `reviewing` status. Reviewers will be notified.
  operationId: adminSubmitDeployment
  tags:
    - Admin
  parameters:
    - in: path
      name: id
      schema:
        type: integer
      description: Deployment ID

  responses:
    "200":
      description: Successful response
    "401":
      description: Unauthorized
    "404":
      description: Deployment not found
    "500":
      $ref: "../../responses/500.yaml"
