post:
  summary: Publish the Deployment. Only draft deployments can be published.
    After publishing, the deployment will be in `deployed` status.
  operationId: adminPublishDeployment
  tags:
    - Admin
  parameters:
    - in: path
      name: id
      schema:
        type: integer
        format: int64
      required: true
      description: Deployment ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            user:
              type: string
              description: who is publishing the deployment
          required:
            - user

  responses:
    "201":
      description: Successful response
    "401":
      description: Unauthorized
    "400":
      $ref: "../../responses/400.yaml"
    "404":
      description: Deployment not found
    "500":
      $ref: "../../responses/500.yaml"
