get:
  summary: Get the result of a deployment
  operationId: adminGetDeploymentResult
  tags:
    - Admin
  parameters:
    - in: path
      name: id
      schema:
        type: integer
        format: int64
      required: true
      description: Deployment ID
  responses:
    "200":
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              error:
                type: string
              logs:
                type: object
                additionalProperties:
                  type: object
            required:
              - status
    "401":
      description: Unauthorized
    "400":
      $ref: "../../responses/400.yaml"
    "404":
      description: Deployment not found
    "500":
      $ref: "../../responses/500.yaml"
