get:
  summary: List Deployments
  operationId: adminListDeployments
  tags:
    - Admin
  parameters:
    - in: query
      name: page
      schema:
        type: integer
      description: Page number (default 1)
    - in: query
      name: page_size
      schema:
        type: integer
      description: Page number (default 10)
    - in: query
      name: name
      schema:
        type: string
      description: Filter by deployment name
  responses:
    "200":
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "../../schemas/Deployment.yaml"
              meta:
                type: object
                properties:
                  total:
                    type: integer
                    format: int64
                    description: Total number of deployments
                  page:
                    type: integer
                    description: Current page number
                  page_size:
                    type: integer
                    description: Number of deployments per page
                required:
                  - total
                  - page
                  - page_size
            required:
              - data
              - meta
    "401":
      description: Unauthorized
    "500":
      $ref: "../../responses/500.yaml"

post:
  summary: Create a new Deployment
  operationId: adminCreateDeployment
  tags:
    - Admin
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              type: string
            reviewers:
              type: array
              items:
                type: string
            user:
              type: string
          required:
            - name
            - user
  responses:
    "201":
      description: Successfully created
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: "../../schemas/Deployment.yaml"
            required:
              - data
    "401":
      description: Unauthorized
    "400":
      $ref: "../../responses/400.yaml"
    "500":
      $ref: "../../responses/500.yaml"
