get:
  summary: List reference config suites
  operationId: adminListReferenceConfigSuites
  tags:
    - Admin
  responses:
    "200":
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "../../schemas/ReferenceConfigSuite.yaml"
            required:
              - data

    "401":
      description: Unauthorized
    "500":
      $ref: "../../responses/500.yaml"
