type: object
properties:
  id:
    type: integer
    format: int64
  actor_id:
    type: integer
    format: int64
  actor_name:
    type: string
  min_actor_version:
    type: string
  content:
    type: object
    additionalProperties:
      type: string
  created_at:
    type: integer
    format: int64
  created_by:
    type: string
  updated_at:
    type: integer
    format: int64
  updated_by:
    type: string

required:
  - id
  - actor_id
  - actor_name
  - content
  - created_at
  - created_by
