type: object
properties:
  id:
    type: integer
    format: int64
  agentId:
    type: integer
    format: int64
  minAgentVersion:
    type: string
  content:
    type: object
  created_at:
    type: integer
    format: int64
  created_by:
    type: string

required:
  - id
  - agentId
  - content
  - created_at
  - created_by
