type: object
properties:
  id:
    type: integer
    format: int64
  agent_id:
    type: integer
    format: int64
  agent_name:
    type: string
  min_agent_version:
    type: string
  content:
    type: object
    additionalProperties:
      type: string
  created_at:
    type: integer
    format: int64
  created_by:
    type: string
  updated_at:
    type: integer
    format: int64
  updated_by:
    type: string

required:
  - id
  - agent_id
  - agent_name
  - content
  - created_at
  - created_by
