openapi: 3.0.0
info:
  title: MAOS Core API
  version: 1.0.0
  description: API for managing invocation jobs and configurations in the MAOS system

servers:
  - url: https://api.example.com/v1

security:
  - bearerAuth: []
  - trace: []

paths:
  /health:
    $ref: "./resources/health.yaml"

  /v1/config:
    $ref: "./resources/config.yaml"

  /v1/invocations/async:
    $ref: "./resources/invocation/create_async.yaml"

  /v1/invocations/sync:
    $ref: "./resources/invocation/create_sync.yaml"

  /v1/invocations/next:
    $ref: "./resources/invocation/next.yaml"

  /v1/invocations/{id}:
    $ref: "./resources/invocation/get.yaml"

  /v1/invocations/{invoke_id}/response:
    $ref: "./resources/invocation/response.yaml"

  /v1/invocations/{invoke_id}/error:
    $ref: "./resources/invocation/error.yaml"

  /v1/completion/models:
    $ref: "./resources/completion/models.yaml"

  /v1/completion:
    $ref: "./resources/completion/index.yaml"

  /v1/embedding/models:
    $ref: "./resources/embedding/models.yaml"

  /v1/embedding:
    $ref: "./resources/embedding/index.yaml"

  /v1/vector/list:
    $ref: "./resources/vector/list.yaml"

  /v1/vector/collection:
    $ref: "./resources/vector/collections.yaml"

  /v1/vector/collection/{name}:
    $ref: "./resources/vector/collection.yaml"

  /v1/rerank/models:
    $ref: "./resources/rerank/models.yaml"

  /v1/rerank:
    $ref: "./resources/rerank/index.yaml"

  /v1/admin/api_tokens:
    $ref: "./resources/admin/api_tokens.yaml"

  /v1/admin/agents:
    $ref: "./resources/admin/agents.yaml"

  /v1/admin/agents/{id}:
    $ref: "./resources/admin/one_agent.yaml"

  /v1/admin/agents/{id}/config:
    $ref: "./resources/admin/agent_config.yaml"

  /v1/admin/deployments:
    $ref: "./resources/admin/deployments.yaml"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Enter the pre-assigned API key as a bearer token
    trace:
      type: apiKey
      in: header
      name: MAOS-TRACE-ID
      description: The unique trace id.

tags:
  - name: Configuration
    description: Operations related to caller configuration
  - name: Invocation
    description: Operations related to invocation jobs
  - name: Completion
    description: Operations involving LLM completion models
  - name: Embedding
    description: Operations involving embedding models and texts
  - name: VectorStore
    description: Operations involving vector store
  - name: Rerank
    description: Operations involving rerank models and texts
  - name: Admin
    description: Operations involving admin tasks
  - name: Health
    description: Operations related to system health

x-namespaces:
  - Maos
