// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: api_token.sql

package dbsqlc

import (
	"context"
)

const apiTokenFindByID = `-- name: ApiTokenFindByID :one
SELECT t.id, a.id as agent_id, a.queue_id, t.permissions, t.expire_at
FROM api_tokens t
JOIN agents a ON t.agent_id = a.id
WHERE t.id = $1
LIMIT 1
`

type ApiTokenFindByIDRow struct {
	ID          string
	AgentID     int64
	QueueID     int64
	Permissions []string
	ExpireAt    int64
}

func (q *Queries) ApiTokenFindByID(ctx context.Context, db DBTX, id string) (*ApiTokenFindByIDRow, error) {
	row := db.QueryRow(ctx, apiTokenFindByID, id)
	var i ApiTokenFindByIDRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.QueueID,
		&i.Permissions,
		&i.ExpireAt,
	)
	return &i, err
}
