// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: config.sql

package dbsqlc

import (
	"context"
)

const configFindByAgentId = `-- name: ConfigFindByAgentId :one
SELECT id, agent_id, config_suite_id, content, min_agent_version, created_by, created_at, updated_by, updated_at
FROM configs
WHERE agent_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) ConfigFindByAgentId(ctx context.Context, db DBTX, agentID int64) (*Config, error) {
	row := db.QueryRow(ctx, configFindByAgentId, agentID)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.AgentId,
		&i.ConfigSuiteID,
		&i.Content,
		&i.MinAgentVersion,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return &i, err
}

const configInsert = `-- name: ConfigInsert :one
INSERT INTO configs(
    agent_id,
    content,
    created_by,
    min_agent_version
) VALUES (
    $1::bigint,
    $2::jsonb,
    $3::text,
    $4::text
) RETURNING id, agent_id, config_suite_id, content, min_agent_version, created_by, created_at, updated_by, updated_at
`

type ConfigInsertParams struct {
	AgentId         int64
	Content         []byte
	CreatedBy       string
	MinAgentVersion *string
}

func (q *Queries) ConfigInsert(ctx context.Context, db DBTX, arg *ConfigInsertParams) (*Config, error) {
	row := db.QueryRow(ctx, configInsert,
		arg.AgentId,
		arg.Content,
		arg.CreatedBy,
		arg.MinAgentVersion,
	)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.AgentId,
		&i.ConfigSuiteID,
		&i.Content,
		&i.MinAgentVersion,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return &i, err
}
