// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deployment.sql

package dbsqlc

import (
	"context"
)

const deploymentInsert = `-- name: DeploymentInsert :one
INSERT INTO deployments (
  name,
  status,
  reviewers,
  created_by
)
VALUES (
  $1::text,
  COALESCE($2::deployment_status, 'draft'),
  COALESCE($3::text[], '{}'),
  $4::text
)
RETURNING id, name, status, reviewers, config_suite_id, created_by, created_at, approved_by, approved_at, finished_by, finished_at
`

type DeploymentInsertParams struct {
	Name      string
	Status    NullDeploymentStatus
	Reviewers []string
	CreatedBy string
}

func (q *Queries) DeploymentInsert(ctx context.Context, db DBTX, arg *DeploymentInsertParams) (*Deployment, error) {
	row := db.QueryRow(ctx, deploymentInsert,
		arg.Name,
		arg.Status,
		arg.Reviewers,
		arg.CreatedBy,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Reviewers,
		&i.ConfigSuiteID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.FinishedBy,
		&i.FinishedAt,
	)
	return &i, err
}

const deploymentListPaginated = `-- name: DeploymentListPaginated :many
SELECT
  id,
  name,
  status,
  created_at,
  created_by,
  approved_at,
  approved_by,
  finished_at,
  finished_by,
  COUNT(*) OVER() AS total_count
FROM deployments
ORDER BY created_at DESC, id DESC
LIMIT $1::bigint
OFFSET $1 * ($2::bigint - 1)
`

type DeploymentListPaginatedParams struct {
	PageSize interface{}
	Page     int64
}

type DeploymentListPaginatedRow struct {
	ID         int64
	Name       string
	Status     DeploymentStatus
	CreatedAt  int64
	CreatedBy  string
	ApprovedAt *int64
	ApprovedBy *string
	FinishedAt *int64
	FinishedBy *string
	TotalCount int64
}

func (q *Queries) DeploymentListPaginated(ctx context.Context, db DBTX, arg *DeploymentListPaginatedParams) ([]*DeploymentListPaginatedRow, error) {
	rows, err := db.Query(ctx, deploymentListPaginated, arg.PageSize, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DeploymentListPaginatedRow
	for rows.Next() {
		var i DeploymentListPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.FinishedAt,
			&i.FinishedBy,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
