// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queue.sql

package dbsqlc

import (
	"context"
)

const queueInsert = `-- name: QueueInsert :one
INSERT INTO queues(
    name,
    metadata
) VALUES (
    $1::text,
    coalesce($2::jsonb, '{}')
) RETURNING id, name, created_at, metadata, paused_at, updated_at
`

type QueueInsertParams struct {
	Name     string
	Metadata []byte
}

func (q *Queries) QueueInsert(ctx context.Context, db DBTX, arg *QueueInsertParams) (*Queues, error) {
	row := db.QueryRow(ctx, queueInsert, arg.Name, arg.Metadata)
	var i Queues
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Metadata,
		&i.PausedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
